// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ChannelMock is an autogenerated mock type for the IChannel type
type ChannelMock struct {
	mock.Mock
}

// Get provides a mock function with given fields:
func (_m *ChannelMock) Get() {
	_m.Called()
}

type mockConstructorTestingTNewChannelMock interface {
	mock.TestingT
	Cleanup(func())
}

// NewChannelMock creates a new instance of ChannelMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewChannelMock(t mockConstructorTestingTNewChannelMock) *ChannelMock {
	mock := &ChannelMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
