// Code generated by mockery v2.20.2. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// DiscordClientMock is an autogenerated mock type for the IDiscordClient type
type DiscordClientMock struct {
	mock.Mock
}

// Do provides a mock function with given fields: req
func (_m *DiscordClientMock) Do(req *http.Request) (*http.Response, error) {
	ret := _m.Called(req)

	var r0 *http.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(*http.Request) (*http.Response, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(*http.Request) *http.Response); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(*http.Request) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewDiscordClientMock interface {
	mock.TestingT
	Cleanup(func())
}

// NewDiscordClientMock creates a new instance of DiscordClientMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDiscordClientMock(t mockConstructorTestingTNewDiscordClientMock) *DiscordClientMock {
	mock := &DiscordClientMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
